version: "3"
services:
  react-app:
    build: ./frontend
    ports:
      - "5173:5173"
  node-express-api:
    build: ./backend
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgres://user:password@postgres:5432/dbname
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: docker-test
    ports:
      - "5432:5432"
